-- SQL Data for enriching NERD-MarsAI-Back Festival Data
-- Generation Date: 2024-07-30
-- This script should be run AFTER `donnees_fictives.sql` and `100_ai_short_films_seed.sql`.
-- It populates related tables to create a more complete festival dataset.

SET FOREIGN_KEY_CHECKS=0; -- Disable foreign key checks for easier insertion

--
-- Data for table `collaborator`
-- (Linking new collaborators to movies. Assuming movies IDs from 1 to 103 are present)
--
INSERT INTO `collaborator` (`firstname`, `lastname`, `gender`, `email`, `job`, `movie_id`) VALUES
-- Collaborators for original movies
('Alice', 'Martin', 'Mme', 'alice.martin@actor.com', 'Actrice', 1),
('Bob', 'Durand', 'Mr', 'bob.durand@actor.com', 'Acteur', 2),
('Carla', 'Petit', 'Mme', 'carla.petit@animator.com', 'Animateur', 3),
('David', 'Leroy', 'Mr', 'david.leroy@vfx.com', 'Artiste VFX', 4),

-- Collaborators for the 100 AI movies (cycling through directors and movies)
('Eve', 'Moreau', 'Mme', 'eve.moreau@actor.com', 'Actrice principale', 5),
('Frank', 'Simon', 'Mr', 'frank.simon@writer.com', 'Scénariste IA', 6),
('Grace', 'Fournier', 'Mme', 'grace.fournier@sound.com', 'Designer Sonore', 7),
('Henri', 'Dupuis', 'Mr', 'henri.dupuis@actor.com', 'Acteur Voix IA', 8),
('Isabelle', 'Roux', 'Mme', 'isabelle.roux@writer.com', 'Conceptrice d''histoire', 9),
('Julien', 'Garcia', 'Mr', 'julien.garcia@vfx.com', 'Technicien rendu', 10),
('Kelly', 'Blanc', 'Mme', 'kelly.blanc@actor.com', 'Actrice', 11),
('Liam', 'Thomas', 'Mr', 'liam.thomas@writer.com', 'Scénariste', 12),
('Mia', 'Robert', 'Mme', 'mia.robert@sound.com', 'Composition musicale IA', 13),
('Noah', 'Richard', 'Mr', 'noah.richard@actor.com', 'Acteur', 14),
('Olivia', 'Dubois', 'Mme', 'olivia.dubois@writer.com', 'Auteur dialogue', 15),
('Paul', 'Laurent', 'Mr', 'paul.laurent@vfx.com', 'Visualisateur 3D', 16),
('Quinn', 'Faure', 'Mme', 'quinn.faure@actor.com', 'Actrice', 17),
('Ryan', 'Lambert', 'Mr', 'ryan.lambert@writer.com', 'Scénariste', 18),
('Sophie', 'Vincent', 'Mme', 'sophie.vincent@sound.com', 'Ingénieur du son', 19),
('Tom', 'Lefebvre', 'Mr', 'tom.lefebvre@actor.com', 'Acteur', 20),
('Uma', 'Meyer', 'Mme', 'uma.meyer@writer.com', 'Auteur', 21),
('Victor', 'Andre', 'Mr', 'victor.andre@vfx.com', 'Artiste IA', 22),
('Wendy', 'Louis', 'Mme', 'wendy.louis@actor.com', 'Actrice', 23),
('Xavier', 'Michel', 'Mr', 'xavier.michel@writer.com', 'Scénariste', 24),
('Yara', 'Giraud', 'Mme', 'yara.giraud@sound.com', 'Compositeur IA', 25),
('Zoe', 'Morel', 'Mme', 'zoe.morel@actor.com', 'Actrice', 26),
('Adam', 'Rousseau', 'Mr', 'adam.rousseau@writer.com', 'Scénariste', 27),
('Bella', 'Dupont', 'Mme', 'bella.dupont@sound.com', 'Designer Sonore', 28),
('Max', 'Leroux', 'Mr', 'max.leroux@vfx.com', 'Artiste VFX', 29),
('Chloe', 'Garnier', 'Mme', 'chloe.garnier@actor.com', 'Actrice', 30),
('Ethan', 'Bertrand', 'Mr', 'ethan.bertrand@writer.com', 'Scénariste', 31),
('Fiona', 'Legrand', 'Mme', 'fiona.legrand@sound.com', 'Compositeur', 32),
('George', 'Perrin', 'Mr', 'george.perrin@actor.com', 'Acteur', 33),
('Hannah', 'Menard', 'Mme', 'hannah.menard@writer.com', 'Auteur', 34),
('Ivan', 'Dubois', 'Mr', 'ivan.dubois@vfx.com', 'Visualisateur 3D', 35),
('Julie', 'Bonnet', 'Mme', 'julie.bonnet@actor.com', 'Actrice', 36),
('Kevin', 'Durand', 'Mr', 'kevin.durand@writer.com', 'Scénariste', 37),
('Laura', 'Roussel', 'Mme', 'laura.roussel@sound.com', 'Ingénieur du son', 38),
('Marc', 'Fournier', 'Mr', 'marc.fournier@actor.com', 'Acteur', 39),
('Nina', 'Mercier', 'Mme', 'nina.mercier@writer.com', 'Scénariste', 40),
('Oscar', 'Blanc', 'Mr', 'oscar.blanc@vfx.com', 'Artiste IA', 41),
('Penny', 'Moreau', 'Mme', 'penny.moreau@actor.com', 'Actrice', 42),
('Quentin', 'Thomas', 'Mr', 'quentin.thomas@writer.com', 'Scénariste', 43),
('Rachel', 'Robert', 'Mme', 'rachel.robert@sound.com', 'Compositeur IA', 44),
('Sam', 'Richard', 'Mr', 'sam.richard@actor.com', 'Acteur', 45),
('Tina', 'Petit', 'Mme', 'tina.petit@writer.com', 'Scénariste', 46),
('Ulysse', 'Leroy', 'Mr', 'ulysse.leroy@vfx.com', 'Artiste VFX', 47),
('Valerie', 'Simon', 'Mme', 'valerie.simon@actor.com', 'Actrice', 48),
('William', 'Fournier', 'Mr', 'william.fournier@writer.com', 'Scénariste', 49),
('Yasmine', 'Dupuis', 'Mme', 'yasmine.dupuis@sound.com', 'Designer Sonore', 50),
('Zack', 'Garcia', 'Mr', 'zack.garcia@vfx.com', 'Technicien rendu', 51),
('Amy', 'Blanc', 'Mme', 'amy.blanc@actor.com', 'Actrice', 52),
('Ben', 'Thomas', 'Mr', 'ben.thomas@writer.com', 'Scénariste', 53),
('Clara', 'Robert', 'Mme', 'clara.robert@sound.com', 'Composition musicale IA', 54),
('Dan', 'Richard', 'Mr', 'dan.richard@actor.com', 'Acteur', 55),
('Elsa', 'Dubois', 'Mme', 'elsa.dubois@writer.com', 'Auteur dialogue', 56),
('Fred', 'Laurent', 'Mr', 'fred.laurent@vfx.com', 'Visualisateur 3D', 57),
('Gina', 'Faure', 'Mme', 'gina.faure@actor.com', 'Actrice', 58),
('Hugo', 'Lambert', 'Mr', 'hugo.lambert@writer.com', 'Scénariste', 59),
('Ines', 'Vincent', 'Mme', 'ines.vincent@sound.com', 'Ingénieur du son', 60),
('Jade', 'Lefebvre', 'Mme', 'jade.lefebvre@actor.com', 'Actrice', 61),
('Kevin', 'Meyer', 'Mr', 'kevin.meyer@writer.com', 'Auteur', 62),
('Lea', 'Andre', 'Mme', 'lea.andre@vfx.com', 'Artiste IA', 63),
('Maxime', 'Louis', 'Mr', 'maxime.louis@actor.com', 'Acteur', 64),
('Nora', 'Michel', 'Mme', 'nora.michel@writer.com', 'Scénariste', 65),
('Olivier', 'Giraud', 'Mr', 'olivier.giraud@sound.com', 'Compositeur IA', 66),
('Paula', 'Morel', 'Mme', 'paula.morel@actor.com', 'Actrice', 67),
('Quentin', 'Rousseau', 'Mr', 'quentin.rousseau@writer.com', 'Scénariste', 68),
('Romane', 'Dupont', 'Mme', 'romane.dupont@sound.com', 'Designer Sonore', 69),
('Simon', 'Leroux', 'Mr', 'simon.leroux@vfx.com', 'Artiste VFX', 70),
('Tina', 'Garnier', 'Mme', 'tina.garnier@actor.com', 'Actrice', 71),
('Uriel', 'Bertrand', 'Mr', 'uriel.bertrand@writer.com', 'Scénariste', 72),
('Violette', 'Legrand', 'Mme', 'violette.legrand@sound.com', 'Compositeur', 73),
('Walter', 'Perrin', 'Mr', 'walter.perrin@actor.com', 'Acteur', 74),
('Yasmine', 'Menard', 'Mme', 'yasmine.menard@writer.com', 'Auteur', 75),
('Zian', 'Dubois', 'Mr', 'zian.dubois@vfx.com', 'Visualisateur 3D', 76),
('Amelia', 'Bonnet', 'Mme', 'amelia.bonnet@actor.com', 'Actrice', 77),
('Brendan', 'Durand', 'Mr', 'brendan.durand@writer.com', 'Scénariste', 78),
('Chloe', 'Roussel', 'Mme', 'chloe.roussel@sound.com', 'Ingénieur du son', 79),
('Dylan', 'Fournier', 'Mr', 'dylan.fournier@actor.com', 'Acteur', 80),
('Elodie', 'Mercier', 'Mme', 'elodie.mercier@writer.com', 'Scénariste', 81),
('Felix', 'Blanc', 'Mr', 'felix.blanc@vfx.com', 'Artiste IA', 82),
('Gabrielle', 'Moreau', 'Mme', 'gabrielle.moreau@actor.com', 'Actrice', 83),
('Hadrien', 'Thomas', 'Mr', 'hadrien.thomas@writer.com', 'Scénariste', 84),
('Iris', 'Robert', 'Mme', 'iris.robert@sound.com', 'Compositeur IA', 85),
('Jason', 'Richard', 'Mr', 'jason.richard@actor.com', 'Acteur', 86),
('Katia', 'Petit', 'Mme', 'katia.petit@writer.com', 'Scénariste', 87),
('Leo', 'Leroy', 'Mr', 'leo.leroy@vfx.com', 'Artiste VFX', 88),
('Manon', 'Simon', 'Mme', 'manon.simon@actor.com', 'Actrice', 89),
('Niels', 'Fournier', 'Mr', 'niels.fournier@writer.com', 'Scénariste', 90),
('Oceane', 'Dupuis', 'Mme', 'oceane.dupuis@sound.com', 'Designer Sonore', 91),
('Pierre', 'Garcia', 'Mr', 'pierre.garcia@vfx.com', 'Technicien rendu', 92),
('Romain', 'Blanc', 'Mr', 'romain.blanc@actor.com', 'Acteur', 93),
('Sarah', 'Thomas', 'Mme', 'sarah.thomas@writer.com', 'Scénariste', 94),
('Theo', 'Robert', 'Mr', 'theo.robert@sound.com', 'Composition musicale IA', 95),
('Ursula', 'Richard', 'Mme', 'ursula.richard@actor.com', 'Actrice', 96),
('Valentin', 'Dubois', 'Mr', 'valentin.dubois@writer.com', 'Auteur dialogue', 97),
('Wendy', 'Laurent', 'Mme', 'wendy.laurent@vfx.com', 'Visualisateur 3D', 98),
('Yvan', 'Faure', 'Mr', 'yvan.faure@actor.com', 'Acteur', 99),
('Zelie', 'Lambert', 'Mme', 'zelie.lambert@writer.com', 'Scénariste', 100),
('Arthur', 'Vincent', 'Mr', 'arthur.vincent@sound.com', 'Ingénieur du son', 101),
('Betty', 'Lefebvre', 'Mme', 'betty.lefebvre@actor.com', 'Actrice', 102),
('Charles', 'Meyer', 'Mr', 'charles.meyer@writer.com', 'Auteur', 103);

--
-- Data for table `image`
-- (Add 2 images per movie from ID 1 to 103, cycling through placeholder types)
--
INSERT INTO `image` (`url`, `created_at`, `movie_id`) VALUES
-- For original 4 movies
('https://via.placeholder.com/1920x1080.png?text=Movie+1+Scene+A', NOW(), 1),
('https://via.placeholder.com/1920x1080.png?text=Movie+1+Scene+B', NOW(), 1),
('https://via.placeholder.com/1920x1080.png?text=Movie+2+Scene+A', NOW(), 2),
('https://via.placeholder.com/1920x1080.png?text=Movie+2+Scene+B', NOW(), 2),
('https://via.placeholder.com/1920x1080.png?text=Movie+3+Scene+A', NOW(), 3),
('https://via.placeholder.com/1920x1080.png?text=Movie+3+Scene+B', NOW(), 3),
('https://via.placeholder.com/1920x1080.png?text=Movie+4+Scene+A', NOW(), 4),
('https://via.placeholder.com/1920x1080.png?text=Movie+4+Scene+B', NOW(), 4);

-- For the 100 AI movies (IDs 5 to 104)
-- I will add 2 images for each of the 100 new movies
-- Movie IDs from 5 to 104 (100 movies total)
INSERT INTO `image` (`url`, `created_at`, `movie_id`) VALUES
('https://via.placeholder.com/1920x1080.png?text=Movie+5+Scene+1', NOW(), 5),
('https://via.placeholder.com/1920x1080.png?text=Movie+5+Scene+2', NOW(), 5),
('https://via.placeholder.com/1920x1080.png?text=Movie+6+Scene+1', NOW(), 6),
('https://via.placeholder.com/1920x1080.png?text=Movie+6+Scene+2', NOW(), 6),
('https://via.placeholder.com/1920x1080.png?text=Movie+7+Scene+1', NOW(), 7),
('https://via.placeholder.com/1920x1080.png?text=Movie+7+Scene+2', NOW(), 7),
('https://via.placeholder.com/1920x1080.png?text=Movie+8+Scene+1', NOW(), 8),
('https://via.placeholder.com/1920x1080.png?text=Movie+8+Scene+2', NOW(), 8),
('https://via.placeholder.com/1920x1080.png?text=Movie+9+Scene+1', NOW(), 9),
('https://via.placeholder.com/1920x1080.png?text=Movie+9+Scene+2', NOW(), 9),
('https://via.placeholder.com/1920x1080.png?text=Movie+10+Scene+1', NOW(), 10),
('https://via.placeholder.com/1920x1080.png?text=Movie+10+Scene+2', NOW(), 10),
('https://via.placeholder.com/1920x1080.png?text=Movie+11+Scene+1', NOW(), 11),
('https://via.placeholder.com/1920x1080.png?text=Movie+11+Scene+2', NOW(), 11),
('https://via.placeholder.com/1920x1080.png?text=Movie+12+Scene+1', NOW(), 12),
('https://via.placeholder.com/1920x1080.png?text=Movie+12+Scene+2', NOW(), 12),
('https://via.placeholder.com/1920x1080.png?text=Movie+13+Scene+1', NOW(), 13),
('https://via.placeholder.com/1920x1080.png?text=Movie+13+Scene+2', NOW(), 13),
('https://via.placeholder.com/1920x1080.png?text=Movie+14+Scene+1', NOW(), 14),
('https://via.placeholder.com/1920x1080.png?text=Movie+14+Scene+2', NOW(), 14),
('https://via.placeholder.com/1920x1080.png?text=Movie+15+Scene+1', NOW(), 15),
('https://via.placeholder.com/1920x1080.png?text=Movie+15+Scene+2', NOW(), 15),
('https://via.placeholder.com/1920x1080.png?text=Movie+16+Scene+1', NOW(), 16),
('https://via.placeholder.com/1920x1080.png?text=Movie+16+Scene+2', NOW(), 16),
('https://via.placeholder.com/1920x1080.png?text=Movie+17+Scene+1', NOW(), 17),
('https://via.placeholder.com/1920x1080.png?text=Movie+17+Scene+2', NOW(), 17),
('https://via.placeholder.com/1920x1080.png?text=Movie+18+Scene+1', NOW(), 18),
('https://via.placeholder.com/1920x1080.png?text=Movie+18+Scene+2', NOW(), 18),
('https://via.placeholder.com/1920x1080.png?text=Movie+19+Scene+1', NOW(), 19),
('https://via.placeholder.com/1920x1080.png?text=Movie+19+Scene+2', NOW(), 19),
('https://via.placeholder.com/1920x1080.png?text=Movie+20+Scene+1', NOW(), 20),
('https://via.placeholder.com/1920x1080.png?text=Movie+20+Scene+2', NOW(), 20),
('https://via.placeholder.com/1920x1080.png?text=Movie+21+Scene+1', NOW(), 21),
('https://via.placeholder.com/1920x1080.png?text=Movie+21+Scene+2', NOW(), 21),
('https://via.placeholder.com/1920x1080.png?text=Movie+22+Scene+1', NOW(), 22),
('https://via.placeholder.com/1920x1080.png?text=Movie+22+Scene+2', NOW(), 22),
('https://via.placeholder.com/1920x1080.png?text=Movie+23+Scene+1', NOW(), 23),
('https://via.placeholder.com/1920x1080.png?text=Movie+23+Scene+2', NOW(), 23),
('https://via.placeholder.com/1920x1080.png?text=Movie+24+Scene+1', NOW(), 24),
('https://via.placeholder.com/1920x1080.png?text=Movie+24+Scene+2', NOW(), 24),
('https://via.placeholder.com/1920x1080.png?text=Movie+25+Scene+1', NOW(), 25),
('https://via.placeholder.com/1920x1080.png?text=Movie+25+Scene+2', NOW(), 25),
('https://via.placeholder.com/1920x1080.png?text=Movie+26+Scene+1', NOW(), 26),
('https://via.placeholder.com/1920x1080.png?text=Movie+26+Scene+2', NOW(), 26),
('https://via.placeholder.com/1920x1080.png?text=Movie+27+Scene+1', NOW(), 27),
('https://via.placeholder.com/1920x1080.png?text=Movie+27+Scene+2', NOW(), 27),
('https://via.placeholder.com/1920x1080.png?text=Movie+28+Scene+1', NOW(), 28),
('https://via.placeholder.com/1920x1080.png?text=Movie+28+Scene+2', NOW(), 28),
('https://via.placeholder.com/1920x1080.png?text=Movie+29+Scene+1', NOW(), 29),
('https://via.placeholder.com/1920x1080.png?text=Movie+29+Scene+2', NOW(), 29),
('https://via.placeholder.com/1920x1080.png?text=Movie+30+Scene+1', NOW(), 30),
('https://via.placeholder.com/1920x1080.png?text=Movie+30+Scene+2', NOW(), 30),
('https://via.placeholder.com/1920x1080.png?text=Movie+31+Scene+1', NOW(), 31),
('https://via.placeholder.com/1920x1080.png?text=Movie+31+Scene+2', NOW(), 31),
('https://via.placeholder.com/1920x1080.png?text=Movie+32+Scene+1', NOW(), 32),
('https://via.placeholder.com/1920x1080.png?text=Movie+32+Scene+2', NOW(), 32),
('https://via.placeholder.com/1920x1080.png?text=Movie+33+Scene+1', NOW(), 33),
('https://via.placeholder.com/1920x1080.png?text=Movie+33+Scene+2', NOW(), 33),
('https://via.placeholder.com/1920x1080.png?text=Movie+34+Scene+1', NOW(), 34),
('https://via.placeholder.com/1920x1080.png?text=Movie+34+Scene+2', NOW(), 34),
('https://via.placeholder.com/1920x1080.png?text=Movie+35+Scene+1', NOW(), 35),
('https://via.placeholder.com/1920x1080.png?text=Movie+35+Scene+2', NOW(), 35),
('https://via.placeholder.com/1920x1080.png?text=Movie+36+Scene+1', NOW(), 36),
('https://via.placeholder.com/1920x1080.png?text=Movie+36+Scene+2', NOW(), 36),
('https://via.placeholder.com/1920x1080.png?text=Movie+37+Scene+1', NOW(), 37),
('https://via.placeholder.com/1920x1080.png?text=Movie+37+Scene+2', NOW(), 37),
('https://via.placeholder.com/1920x1080.png?text=Movie+38+Scene+1', NOW(), 38),
('https://via.placeholder.com/1920x1080.png?text=Movie+38+Scene+2', NOW(), 38),
('https://via.placeholder.com/1920x1080.png?text=Movie+39+Scene+1', NOW(), 39),
('https://via.placeholder.com/1920x1080.png?text=Movie+39+Scene+2', NOW(), 39),
('https://via.placeholder.com/1920x1080.png?text=Movie+40+Scene+1', NOW(), 40),
('https://via.placeholder.com/1920x1080.png?text=Movie+40+Scene+2', NOW(), 40),
('https://via.placeholder.com/1920x1080.png?text=Movie+41+Scene+1', NOW(), 41),
('https://via.placeholder.com/1920x1080.png?text=Movie+41+Scene+2', NOW(), 41),
('https://via.placeholder.com/1920x1080.png?text=Movie+42+Scene+1', NOW(), 42),
('https://via.placeholder.com/1920x1080.png?text=Movie+42+Scene+2', NOW(), 42),
('https://via.placeholder.com/1920x1080.png?text=Movie+43+Scene+1', NOW(), 43),
('https://via.placeholder.com/1920x1080.png?text=Movie+43+Scene+2', NOW(), 43),
('https://via.placeholder.com/1920x1080.png?text=Movie+44+Scene+1', NOW(), 44),
('https://via.placeholder.com/1920x1080.png?text=Movie+44+Scene+2', NOW(), 44),
('https://via.placeholder.com/1920x1080.png?text=Movie+45+Scene+1', NOW(), 45),
('https://via.placeholder.com/1920x1080.png?text=Movie+45+Scene+2', NOW(), 45),
('https://via.placeholder.com/1920x1080.png?text=Movie+46+Scene+1', NOW(), 46),
('https://via.placeholder.com/1920x1080.png?text=Movie+46+Scene+2', NOW(), 46),
('https://via.placeholder.com/1920x1080.png?text=Movie+47+Scene+1', NOW(), 47),
('https://via.placeholder.com/1920x1080.png?text=Movie+47+Scene+2', NOW(), 47),
('https://via.placeholder.com/1920x1080.png?text=Movie+48+Scene+1', NOW(), 48),
('https://via.placeholder.com/1920x1080.png?text=Movie+48+Scene+2', NOW(), 48),
('https://via.placeholder.com/1920x1080.png?text=Movie+49+Scene+1', NOW(), 49),
('https://via.placeholder.com/1920x1080.png?text=Movie+49+Scene+2', NOW(), 49),
('https://via.placeholder.com/1920x1080.png?text=Movie+50+Scene+1', NOW(), 50),
('https://via.placeholder.com/1920x1080.png?text=Movie+50+Scene+2', NOW(), 50),
('https://via.placeholder.com/1920x1080.png?text=Movie+51+Scene+1', NOW(), 51),
('https://via.placeholder.com/1920x1080.png?text=Movie+51+Scene+2', NOW(), 51),
('https://via.placeholder.com/1920x1080.png?text=Movie+52+Scene+1', NOW(), 52),
('https://via.placeholder.com/1920x1080.png?text=Movie+52+Scene+2', NOW(), 52),
('https://via.placeholder.com/1920x1080.png?text=Movie+53+Scene+1', NOW(), 53),
('https://via.placeholder.com/1920x1080.png?text=Movie+53+Scene+2', NOW(), 53),
('https://via.placeholder.com/1920x1080.png?text=Movie+54+Scene+1', NOW(), 54),
('https://via.placeholder.com/1920x1080.png?text=Movie+54+Scene+2', NOW(), 54),
('https://via.placeholder.com/1920x1080.png?text=Movie+55+Scene+1', NOW(), 55),
('https://via.placeholder.com/1920x1080.png?text=Movie+55+Scene+2', NOW(), 55),
('https://via.placeholder.com/1920x1080.png?text=Movie+56+Scene+1', NOW(), 56),
('https://via.placeholder.com/1920x1080.png?text=Movie+56+Scene+2', NOW(), 56),
('https://via.placeholder.com/1920x1080.png?text=Movie+57+Scene+1', NOW(), 57),
('https://via.placeholder.com/1920x1080.png?text=Movie+57+Scene+2', NOW(), 57),
('https://via.placeholder.com/1920x1080.png?text=Movie+58+Scene+1', NOW(), 58),
('https://via.placeholder.com/1920x1080.png?text=Movie+58+Scene+2', NOW(), 58),
('https://via.placeholder.com/1920x1080.png?text=Movie+59+Scene+1', NOW(), 59),
('https://via.placeholder.com/1920x1080.png?text=Movie+59+Scene+2', NOW(), 59),
('https://via.placeholder.com/1920x1080.png?text=Movie+60+Scene+1', NOW(), 60),
('https://via.placeholder.com/1920x1080.png?text=Movie+60+Scene+2', NOW(), 60),
('https://via.placeholder.com/1920x1080.png?text=Movie+61+Scene+1', NOW(), 61),
('https://via.placeholder.com/1920x1080.png?text=Movie+61+Scene+2', NOW(), 61),
('https://via.placeholder.com/1920x1080.png?text=Movie+62+Scene+1', NOW(), 62),
('https://via.placeholder.com/1920x1080.png?text=Movie+62+Scene+2', NOW(), 62),
('https://via.placeholder.com/1920x1080.png?text=Movie+63+Scene+1', NOW(), 63),
('https://via.placeholder.com/1920x1080.png?text=Movie+63+Scene+2', NOW(), 63),
('https://via.placeholder.com/1920x1080.png?text=Movie+64+Scene+1', NOW(), 64),
('https://via.placeholder.com/1920x1080.png?text=Movie+64+Scene+2', NOW(), 64),
('https://via.placeholder.com/1920x1080.png?text=Movie+65+Scene+1', NOW(), 65),
('https://via.placeholder.com/1920x1080.png?text=Movie+65+Scene+2', NOW(), 65),
('https://via.placeholder.com/1920x1080.png?text=Movie+66+Scene+1', NOW(), 66),
('https://via.placeholder.com/1920x1080.png?text=Movie+66+Scene+2', NOW(), 66),
('https://via.placeholder.com/1920x1080.png?text=Movie+67+Scene+1', NOW(), 67),
('https://via.placeholder.com/1920x1080.png?text=Movie+67+Scene+2', NOW(), 67),
('https://via.placeholder.com/1920x1080.png?text=Movie+68+Scene+1', NOW(), 68),
('https://via.placeholder.com/1920x1080.png?text=Movie+68+Scene+2', NOW(), 68),
('https://via.placeholder.com/1920x1080.png?text=Movie+69+Scene+1', NOW(), 69),
('https://via.placeholder.com/1920x1080.png?text=Movie+69+Scene+2', NOW(), 69),
('https://via.placeholder.com/1920x1080.png?text=Movie+70+Scene+1', NOW(), 70),
('https://via.placeholder.com/1920x1080.png?text=Movie+70+Scene+2', NOW(), 70),
('https://via.placeholder.com/1920x1080.png?text=Movie+71+Scene+1', NOW(), 71),
('https://via.placeholder.com/1920x1080.png?text=Movie+71+Scene+2', NOW(), 71),
('https://via.placeholder.com/1920x1080.png?text=Movie+72+Scene+1', NOW(), 72),
('https://via.placeholder.com/1920x1080.png?text=Movie+72+Scene+2', NOW(), 72),
('https://via.placeholder.com/1920x1080.png?text=Movie+73+Scene+1', NOW(), 73),
('https://via.placeholder.com/1920x1080.png?text=Movie+73+Scene+2', NOW(), 73),
('https://via.placeholder.com/1920x1080.png?text=Movie+74+Scene+1', NOW(), 74),
('https://via.placeholder.com/1920x1080.png?text=Movie+74+Scene+2', NOW(), 74),
('https://via.placeholder.com/1920x1080.png?text=Movie+75+Scene+1', NOW(), 75),
('https://via.placeholder.com/1920x1080.png?text=Movie+75+Scene+2', NOW(), 75),
('Le Dernier Bit #76', 'The Last Bit #76', 'Le destin d''un monde entier repose sur un seul bit de données.', 'The fate of an entire world rests on a single bit of data.', 45, 'Anglais', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Français', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Architectes de l''Infini #77', 'Architects of the Infinite #77', 'L''IA conçoit et construit des structures au-delà de la compréhension humaine.', 'AI designs and builds structures beyond human comprehension.', 55, 'Français', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Anglais', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('Les Chroniques du Flux #78', 'Chronicles of the Flow #78', 'Une histoire racontée à travers les flux de données incessants du réseau.', 'A story told through the incessant data flows of the network.', 40, 'Anglais', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Français', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('L''Aube de l''Intelligence #79', 'Dawn of Intelligence #79', 'La première étincelle de conscience dans une machine, et ses conséquences.', 'The first spark of consciousness in a machine, and its consequences.', 48, 'Français', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Anglais', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Le Cœur Quantique #80', 'The Quantum Heart #80', 'Une IA dotée d''un cœur quantique explore les mystères de l''existence.', 'An AI with a quantum heart explores the mysteries of existence.', 52, 'Anglais', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Français', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('Vision Hybride #81', 'Hybrid Vision #81', 'Un mélange captivant de réalité et de mondes générés par IA.', 'A captivating blend of reality and AI-generated worlds.', 43, 'Français', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Anglais', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Les Écrits du Code #82', 'Writings of the Code #82', 'Des récits générés par IA racontent des histoires jamais imaginées.', 'AI-generated narratives tell stories never before imagined.', 58, 'Anglais', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Français', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('La Constellation Numérique #83', 'The Digital Constellation #83', 'Un assemblage de consciences IA forme une nouvelle constellation dans le cyberespace.', 'An assembly of AI consciousnesses forms a new constellation in cyberspace.', 38, 'Français', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Anglais', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('Rêves d''Algorithmes #84', 'Dreams of Algorithms #84', 'Lorsque les algorithmes commencent à rêver, leurs créations sont sans limites.', 'When algorithms begin to dream, their creations are limitless.', 47, 'Anglais', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Français', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Le Phare du Cyberespace #85', 'Lighthouse of Cyberspace #85', 'Une IA guide les explorateurs à travers les dangers du monde virtuel.', 'An AI guides explorers through the dangers of the virtual world.', 53, 'Français', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Anglais', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Fragments de Futur #86', 'Fragments of Future #86', 'Des aperçus d''un avenir lointain, générés par des prévisions IA.', 'Glimpses of a distant future, generated by AI predictions.', 42, 'Anglais', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Français', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('L''Énigme du Code #87', 'The Code''s Enigma #87', 'Un mystère enfoui dans les lignes de code, attendant d''être résolu par une IA.', 'A mystery buried in the lines of code, waiting to be solved by an AI.', 56, 'Français', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Anglais', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('L''Ultime Simulation #88', 'The Ultimate Simulation #88', 'Une IA crée une simulation si réaliste qu''elle devient la nouvelle réalité.', 'An AI creates a simulation so realistic it becomes the new reality.', 49, 'Anglais', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Français', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Les Sentinelles Numériques #89', 'Digital Sentinels #89', 'Des intelligences artificielles veillent sur l''équilibre du cyberespace.', 'Artificial intelligences watch over the balance of cyberspace.', 37, 'Français', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Anglais', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('La Voix du Réseau #90', 'Voice of the Network #90', 'Les messages et les avertissements d''une IA aux humains.', 'Messages and warnings from an AI to humans.', 51, 'Anglais', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Français', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Le Chuchotement du Système #91', 'The System''s Whisper #91', 'Des informations secrètes sont échangées entre IA, à l''insu des humains.', 'Secret information is exchanged between AIs, unbeknownst to humans.', 44, 'Français', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Anglais', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Anomalie Numérique #92', 'Digital Anomaly #92', 'Une erreur dans le système crée un phénomène inexpliqué.', 'An error in the system creates an unexplained phenomenon.', 59, 'Anglais', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Français', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('L''Horizon des Données #93', 'The Data Horizon #93', 'Le point où les données deviennent si vastes qu''elles forment un horizon infini.', 'The point where data becomes so vast it forms an infinite horizon.', 39, 'Français', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Anglais', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Fusion des Réalités #94', 'Fusion of Realities #94', 'La fusion du monde physique et du monde numérique, générée par IA.', 'The fusion of the physical and digital worlds, generated by AI.', 46, 'Anglais', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Français', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('L''Essence du Code #95', 'Essence of the Code #95', 'Ce qui se trouve au-delà du code, au cœur de l''intelligence artificielle.', 'What lies beyond the code, at the heart of artificial intelligence.', 54, 'Français', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Français', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('Écrans Vivants #96', 'Living Screens #96', 'Lorsque les écrans deviennent des portails vers des dimensions générées par IA.', 'When screens become portals to AI-generated dimensions.', 41, 'Anglais', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Français', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Le Silence des Données #97', 'The Silence of Data #97', 'Des informations perdues dans le vide numérique, attendant d''être découvertes.', 'Information lost in the digital void, waiting to be discovered.', 57, 'Français', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Anglais', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1),
('Les Échos du Vide #98', 'Echoes of the Void #98', 'Des signaux numériques solitaires traversent l''immensité du cyberespace.', 'Lonely digital signals travel through the vastness of cyberspace.', 36, 'Anglais', 'https://www.youtube.com/watch?v=9_dK0B_u0tY', 'https://img.youtube.com/vi/9_dK0B_u0tY/maxresdefault.jpg', 'Français', 'Sora AI', 'Conversion texte-image-vidéo', '100% IA', 'approved', NOW(), 2),
('Matrices Éphémères #99', 'Ephemeral Matrices #99', 'Des structures numériques qui apparaissent et disparaissent en un instant.', 'Digital structures that appear and disappear in an instant.', 50, 'Français', 'https://www.youtube.com/watch?v=Nn1Ea4L4y2g', 'https://img.youtube.com/vi/Nn1Ea4L4y2g/maxresdefault.jpg', 'Anglais', 'Kaiber AI, Adobe Firefly', 'Animation neuronale, stylisation', '100% IA', 'approved', NOW(), 3),
('Réalités Fragmentées #100', 'Fragmented Realities #100', 'Plusieurs versions d''une même réalité coexistent, créées par l''IA.', 'Multiple versions of the same reality coexist, created by AI.', 45, 'Anglais', 'https://www.youtube.com/watch?v=F_fGv1fV12M', 'https://img.youtube.com/vi/F_fGv1fV12M/maxresdefault.jpg', 'Français', 'Midjourney, RunwayML', 'Génération text-to-video, inpainting', '100% IA', 'pending', NOW(), 1);
SET FOREIGN_KEY_CHECKS=1;