SET NAMES utf8mb4;
-- SQL Data for enriching NERD-MarsAI-Back Festival Data
-- Generation Date: 2024-07-30
-- This script should be run AFTER `donnees_fictives.sql` and `100_ai_short_films_seed.sql`.
-- It populates related tables to create a more complete festival dataset.

SET FOREIGN_KEY_CHECKS=0; -- Disable foreign key checks for easier insertion

TRUNCATE TABLE `collaborator`;
TRUNCATE TABLE `rating`;

--
-- Data for table `collaborator`
-- (Linking new collaborators to movies. Assuming movies IDs from 1 to 104 are present)
--
INSERT INTO `collaborator` (`firstname`, `lastname`, `gender`, `email`, `job`, `movie_id`) VALUES
-- Collaborators for original movies (IDs 1-4)
('Alice', 'Martin', 'Mme', 'alice.martin@actor.com', 'Actrice', 1),
('Bob', 'Durand', 'Mr', 'bob.durand@actor.com', 'Acteur', 2),
('Carla', 'Petit', 'Mme', 'carla.petit@animator.com', 'Animateur', 3),
('David', 'Leroy', 'Mr', 'david.leroy@vfx.com', 'Artiste VFX', 4),

-- Collaborators for the 100 AI movies (IDs 5 to 104) - adding 2 per movie
('Eve', 'Moreau', 'Mme', 'eve.moreau@collaborator.com', 'Actrice principale', 5),
('Frank', 'Simon', 'Mr', 'frank.simon@collaborator.com', 'Scénariste IA', 5),
('Grace', 'Fournier', 'Mme', 'grace.fournier@collaborator.com', 'Designer Sonore', 6),
('Henri', 'Dupuis', 'Mr', 'henri.dupuis@collaborator.com', 'Acteur Voix IA', 6),
('Isabelle', 'Roux', 'Mme', 'isabelle.roux@collaborator.com', 'Conceptrice d''histoire', 7),
('Julien', 'Garcia', 'Mr', 'julien.garcia@collaborator.com', 'Technicien rendu', 7),
('Kelly', 'Blanc', 'Mme', 'kelly.blanc@collaborator.com', 'Actrice', 8),
('Liam', 'Thomas', 'Mr', 'liam.thomas@collaborator.com', 'Scénariste', 8),
('Mia', 'Robert', 'Mme', 'mia.robert@collaborator.com', 'Composition musicale IA', 9),
('Noah', 'Richard', 'Mr', 'noah.richard@collaborator.com', 'Acteur', 9),
('Olivia', 'Dubois', 'Mme', 'olivia.dubois@collaborator.com', 'Auteur dialogue', 10),
('Paul', 'Laurent', 'Mr', 'paul.laurent@collaborator.com', 'Visualisateur 3D', 10),
('Quinn', 'Faure', 'Mme', 'quinn.faure@collaborator.com', 'Actrice', 11),
('Ryan', 'Lambert', 'Mr', 'ryan.lambert@collaborator.com', 'Scénariste', 11),
('Sophie', 'Vincent', 'Mme', 'sophie.vincent@collaborator.com', 'Ingénieur du son', 12),
('Tom', 'Lefebvre', 'Mr', 'tom.lefebvre@collaborator.com', 'Acteur', 12),
('Uma', 'Meyer', 'Mme', 'uma.meyer@collaborator.com', 'Auteur', 13),
('Victor', 'Andre', 'Mr', 'victor.andre@collaborator.com', 'Artiste IA', 13),
('Wendy', 'Louis', 'Mme', 'wendy.louis@collaborator.com', 'Actrice', 14),
('Xavier', 'Michel', 'Mr', 'xavier.michel@collaborator.com', 'Scénariste', 14),
('Yara', 'Giraud', 'Mme', 'yara.giraud@collaborator.com', 'Compositeur IA', 15),
('Zoe', 'Morel', 'Mme', 'zoe.morel@collaborator.com', 'Actrice', 15),
('Adam', 'Rousseau', 'Mr', 'adam.rousseau@collaborator.com', 'Scénariste', 16),
('Bella', 'Dupont', 'Mme', 'bella.dupont@collaborator.com', 'Designer Sonore', 16),
('Max', 'Leroux', 'Mr', 'max.leroux@collaborator.com', 'Artiste VFX', 17),
('Chloe', 'Garnier', 'Mme', 'chloe.garnier@collaborator.com', 'Actrice', 17),
('Ethan', 'Bertrand', 'Mr', 'ethan.bertrand@collaborator.com', 'Scénariste', 18),
('Fiona', 'Legrand', 'Mme', 'fiona.legrand@collaborator.com', 'Compositeur', 18),
('George', 'Perrin', 'Mr', 'george.perrin@collaborator.com', 'Acteur', 19),
('Hannah', 'Menard', 'Mme', 'hannah.menard@collaborator.com', 'Auteur', 19),
('Ivan', 'Dubois', 'Mr', 'ivan.dubois@collaborator.com', 'Visualisateur 3D', 20),
('Julie', 'Bonnet', 'Mme', 'julie.bonnet@collaborator.com', 'Actrice', 20),
('Kevin', 'Durand', 'Mr', 'kevin.durand@collaborator.com', 'Scénariste', 21),
('Laura', 'Roussel', 'Mme', 'laura.roussel@collaborator.com', 'Ingénieur du son', 21),
('Marc', 'Fournier', 'Mr', 'marc.fournier@collaborator.com', 'Acteur', 22),
('Nina', 'Mercier', 'Mme', 'nina.mercier@collaborator.com', 'Scénariste', 22),
('Oscar', 'Blanc', 'Mr', 'oscar.blanc@collaborator.com', 'Artiste IA', 23),
('Penny', 'Moreau', 'Mme', 'penny.moreau@collaborator.com', 'Actrice', 23),
('Quentin', 'Thomas', 'Mr', 'quentin.thomas@collaborator.com', 'Scénariste', 24),
('Rachel', 'Robert', 'Mme', 'rachel.robert@collaborator.com', 'Compositeur IA', 24),
('Sam', 'Richard', 'Mr', 'sam.richard@collaborator.com', 'Acteur', 25),
('Tina', 'Petit', 'Mme', 'tina.petit@collaborator.com', 'Scénariste', 25),
('Ulysse', 'Leroy', 'Mr', 'ulysse.leroy@collaborator.com', 'Artiste VFX', 26),
('Valerie', 'Simon', 'Mme', 'valerie.simon@collaborator.com', 'Actrice', 26),
('William', 'Fournier', 'Mr', 'william.fournier@collaborator.com', 'Scénariste', 27),
('Yasmine', 'Dupuis', 'Mme', 'yasmine.dupuis@collaborator.com', 'Designer Sonore', 27),
('Zack', 'Garcia', 'Mr', 'zack.garcia@collaborator.com', 'Technicien rendu', 28),
('Amy', 'Blanc', 'Mme', 'amy.blanc@collaborator.com', 'Actrice', 28),
('Ben', 'Thomas', 'Mr', 'ben.thomas@collaborator.com', 'Scénariste', 29),
('Clara', 'Robert', 'Mme', 'clara.robert@collaborator.com', 'Composition musicale IA', 29),
('Dan', 'Richard', 'Mr', 'dan.richard@collaborator.com', 'Acteur', 30),
('Elsa', 'Dubois', 'Mme', 'elsa.dubois@collaborator.com', 'Auteur dialogue', 30),
('Fred', 'Laurent', 'Mr', 'fred.laurent@collaborator.com', 'Visualisateur 3D', 31),
('Gina', 'Faure', 'Mme', 'gina.faure@collaborator.com', 'Actrice', 31),
('Hugo', 'Lambert', 'Mr', 'hugo.lambert@collaborator.com', 'Scénariste', 32),
('Ines', 'Vincent', 'Mme', 'ines.vincent@collaborator.com', 'Ingénieur du son', 32),
('Jade', 'Lefebvre', 'Mme', 'jade.lefebvre@collaborator.com', 'Actrice', 33),
('Kevin', 'Meyer', 'Mr', 'kevin.meyer@collaborator.com', 'Auteur', 33),
('Lea', 'Andre', 'Mme', 'lea.andre@collaborator.com', 'Artiste IA', 34),
('Maxime', 'Louis', 'Mr', 'maxime.louis@collaborator.com', 'Acteur', 34),
('Nora', 'Michel', 'Mme', 'nora.michel@collaborator.com', 'Scénariste', 35),
('Olivier', 'Giraud', 'Mr', 'olivier.giraud@collaborator.com', 'Compositeur IA', 35),
('Paula', 'Morel', 'Mme', 'paula.morel@collaborator.com', 'Actrice', 36),
('Quentin', 'Rousseau', 'Mr', 'quentin.rousseau@collaborator.com', 'Scénariste', 36),
('Romane', 'Dupont', 'Mme', 'romane.dupont@collaborator.com', 'Designer Sonore', 37),
('Simon', 'Leroux', 'Mr', 'simon.leroux@collaborator.com', 'Artiste VFX', 37),
('Tina', 'Garnier', 'Mme', 'tina.garnier@collaborator.com', 'Actrice', 38),
('Uriel', 'Bertrand', 'Mr', 'uriel.bertrand@collaborator.com', 'Scénariste', 38),
('Violette', 'Legrand', 'Mme', 'violette.legrand@collaborator.com', 'Compositeur', 39),
('Walter', 'Perrin', 'Mr', 'walter.perrin@collaborator.com', 'Acteur', 39),
('Yasmine', 'Menard', 'Mme', 'yasmine.menard@collaborator.com', 'Auteur', 40),
('Zian', 'Dubois', 'Mr', 'zian.dubois@collaborator.com', 'Visualisateur 3D', 40),
('Amelia', 'Bonnet', 'Mme', 'amelia.bonnet@collaborator.com', 'Actrice', 41),
('Brendan', 'Durand', 'Mr', 'brendan.durand@collaborator.com', 'Scénariste', 41),
('Chloe', 'Roussel', 'Mme', 'chloe.roussel@collaborator.com', 'Ingénieur du son', 42),
('Dylan', 'Fournier', 'Mr', 'dylan.fournier@collaborator.com', 'Acteur', 42),
('Elodie', 'Mercier', 'Mme', 'elodie.mercier@collaborator.com', 'Scénariste', 43),
('Felix', 'Blanc', 'Mr', 'felix.blanc@collaborator.com', 'Artiste IA', 43),
('Gabrielle', 'Moreau', 'Mme', 'gabrielle.moreau@collaborator.com', 'Actrice', 44),
('Hadrien', 'Thomas', 'Mr', 'hadrien.thomas@collaborator.com', 'Scénariste', 44),
('Iris', 'Robert', 'Mme', 'iris.robert@collaborator.com', 'Compositeur IA', 45),
('Jason', 'Richard', 'Mr', 'jason.richard@collaborator.com', 'Acteur', 45),
('Katia', 'Petit', 'Mme', 'katia.petit@collaborator.com', 'Scénariste', 46),
('Leo', 'Leroy', 'Mr', 'leo.leroy@collaborator.com', 'Artiste VFX', 46),
('Manon', 'Simon', 'Mme', 'manon.simon@collaborator.com', 'Actrice', 47),
('Niels', 'Fournier', 'Mr', 'niels.fournier@collaborator.com', 'Scénariste', 47),
('Oceane', 'Dupuis', 'Mme', 'oceane.dupuis@collaborator.com', 'Designer Sonore', 48),
('Pierre', 'Garcia', 'Mr', 'pierre.garcia@collaborator.com', 'Technicien rendu', 48),
('Romain', 'Blanc', 'Mr', 'romain.blanc@collaborator.com', 'Acteur', 49),
('Sarah', 'Thomas', 'Mme', 'sarah.thomas@collaborator.com', 'Scénariste', 49),
('Theo', 'Robert', 'Mr', 'theo.robert@collaborator.com', 'Composition musicale IA', 50),
('Ursula', 'Richard', 'Mme', 'ursula.richard@collaborator.com', 'Actrice', 50),
('Valentin', 'Dubois', 'Mr', 'valentin.dubois@collaborator.com', 'Auteur dialogue', 51),
('Wendy', 'Laurent', 'Mme', 'wendy.laurent@collaborator.com', 'Visualisateur 3D', 51),
('Yvan', 'Faure', 'Mr', 'yvan.faure@collaborator.com', 'Acteur', 52),
('Zelie', 'Lambert', 'Mme', 'zelie.lambert@collaborator.com', 'Scénariste', 52),
('Arthur', 'Vincent', 'Mr', 'arthur.vincent@collaborator.com', 'Ingénieur du son', 53),
('Betty', 'Lefebvre', 'Mme', 'betty.lefebvre@collaborator.com', 'Actrice', 53),
('Charles', 'Meyer', 'Mr', 'charles.meyer@collaborator.com', 'Auteur', 54),
('Diana', 'Andre', 'Mme', 'diana.andre@collaborator.com', 'Artiste IA', 54),
('Eric', 'Louis', 'Mr', 'eric.louis@collaborator.com', 'Acteur', 55),
('Fanny', 'Michel', 'Mme', 'fanny.michel@collaborator.com', 'Scénariste', 55),
('Gael', 'Giraud', 'Mr', 'gael.giraud@collaborator.com', 'Compositeur IA', 56),
('Helene', 'Morel', 'Mme', 'helene.morel@collaborator.com', 'Actrice', 56),
('Ivan', 'Rousseau', 'Mr', 'ivan.rousseau@collaborator.com', 'Scénariste', 57),
('Justine', 'Dupont', 'Mme', 'justine.dupont@collaborator.com', 'Designer Sonore', 57),
('Kyle', 'Leroux', 'Mr', 'kyle.leroux@collaborator.com', 'Artiste VFX', 58),
('Lina', 'Garnier', 'Mme', 'lina.garnier@collaborator.com', 'Actrice', 58),
('Maxence', 'Bertrand', 'Mr', 'maxence.bertrand@collaborator.com', 'Scénariste', 59),
('Nora', 'Legrand', 'Mme', 'nora.legrand@collaborator.com', 'Compositeur', 59),
('Oscar', 'Perrin', 'Mr', 'oscar.perrin@collaborator.com', 'Acteur', 60),
('Pauline', 'Menard', 'Mme', 'pauline.menard@collaborator.com', 'Auteur', 60),
('Quentin', 'Dubois', 'Mr', 'quentin.dubois@collaborator.com', 'Visualisateur 3D', 61),
('Rebecca', 'Bonnet', 'Mme', 'rebecca.bonnet@collaborator.com', 'Actrice', 61),
('Stephane', 'Durand', 'Mr', 'stephane.durand@collaborator.com', 'Scénariste', 62),
('Chloe', 'Roussel', 'Mme', 'chloe.roussel@collaborator.com', 'Ingénieur du son', 62),
('Dylan', 'Fournier', 'Mr', 'dylan.fournier@collaborator.com', 'Acteur', 63),
('Elodie', 'Mercier', 'Mme', 'elodie.mercier@collaborator.com', 'Scénariste', 63),
('Felix', 'Blanc', 'Mr', 'felix.blanc@collaborator.com', 'Artiste IA', 64),
('Gabrielle', 'Moreau', 'Mme', 'gabrielle.moreau@collaborator.com', 'Actrice', 64),
('Hadrien', 'Thomas', 'Mr', 'hadrien.thomas@collaborator.com', 'Scénariste', 65),
('Iris', 'Robert', 'Mme', 'iris.robert@collaborator.com', 'Compositeur IA', 65),
('Jason', 'Richard', 'Mr', 'jason.richard@collaborator.com', 'Acteur', 66),
('Katia', 'Petit', 'Mme', 'katia.petit@collaborator.com', 'Scénariste', 66),
('Leo', 'Leroy', 'Mr', 'leo.leroy@collaborator.com', 'Artiste VFX', 67),
('Manon', 'Simon', 'Mme', 'manon.simon@collaborator.com', 'Actrice', 67),
('Niels', 'Fournier', 'Mr', 'niels.fournier@collaborator.com', 'Scénariste', 68),
('Oceane', 'Dupuis', 'Mme', 'oceane.dupuis@collaborator.com', 'Designer Sonore', 68),
('Pierre', 'Garcia', 'Mr', 'pierre.garcia@collaborator.com', 'Technicien rendu', 69),
('Romain', 'Blanc', 'Mr', 'romain.blanc@collaborator.com', 'Acteur', 69),
('Sarah', 'Thomas', 'Mme', 'sarah.thomas@collaborator.com', 'Scénariste', 70),
('Theo', 'Robert', 'Mr', 'theo.robert@collaborator.com', 'Composition musicale IA', 70),
('Ursula', 'Richard', 'Mme', 'ursula.richard@collaborator.com', 'Actrice', 71),
('Valentin', 'Dubois', 'Mr', 'valentin.dubois@collaborator.com', 'Auteur dialogue', 71),
('Wendy', 'Laurent', 'Mme', 'wendy.laurent@collaborator.com', 'Visualisateur 3D', 72),
('Yvan', 'Faure', 'Mr', 'yvan.faure@collaborator.com', 'Acteur', 72),
('Zelie', 'Lambert', 'Mme', 'zelie.lambert@collaborator.com', 'Scénariste', 73),
('Arthur', 'Vincent', 'Mr', 'arthur.vincent@collaborator.com', 'Ingénieur du son', 73),
('Betty', 'Lefebvre', 'Mme', 'betty.lefebvre@collaborator.com', 'Actrice', 74),
('Charles', 'Meyer', 'Mr', 'charles.meyer@collaborator.com', 'Auteur', 74),
('Diana', 'Andre', 'Mme', 'diana.andre@collaborator.com', 'Artiste IA', 75),
('Eric', 'Louis', 'Mr', 'eric.louis@collaborator.com', 'Acteur', 75),
('Fanny', 'Michel', 'Mme', 'fanny.michel@collaborator.com', 'Scénariste', 76),
('Gael', 'Giraud', 'Mr', 'gael.giraud@collaborator.com', 'Compositeur IA', 76),
('Helene', 'Morel', 'Mme', 'helene.morel@collaborator.com', 'Actrice', 77),
('Ivan', 'Rousseau', 'Mr', 'ivan.rousseau@collaborator.com', 'Scénariste', 77),
('Justine', 'Dupont', 'Mme', 'justine.dupont@collaborator.com', 'Designer Sonore', 78),
('Kyle', 'Leroux', 'Mr', 'kyle.leroux@collaborator.com', 'Artiste VFX', 78),
('Lina', 'Garnier', 'Mme', 'lina.garnier@collaborator.com', 'Actrice', 79),
('Maxence', 'Bertrand', 'Mr', 'maxence.bertrand@collaborator.com', 'Scénariste', 79),
('Nora', 'Legrand', 'Mme', 'nora.legrand@collaborator.com', 'Compositeur', 80),
('Oscar', 'Perrin', 'Mr', 'oscar.perrin@collaborator.com', 'Acteur', 80),
('Pauline', 'Menard', 'Mme', 'pauline.menard@collaborator.com', 'Auteur', 81),
('Quentin', 'Dubois', 'Mr', 'quentin.dubois@collaborator.com', 'Visualisateur 3D', 81),
('Rebecca', 'Bonnet', 'Mme', 'rebecca.bonnet@collaborator.com', 'Actrice', 82),
('Stephane', 'Durand', 'Mr', 'stephane.durand@collaborator.com', 'Scénariste', 82),
('Tina', 'Garnier', 'Mme', 'tina.garnier@collaborator.com', 'Ingénieur du son', 83),
('Uriel', 'Bertrand', 'Mr', 'uriel.bertrand@collaborator.com', 'Acteur', 83),
('Violette', 'Legrand', 'Mme', 'violette.legrand@collaborator.com', 'Scénariste', 84),
('Walter', 'Perrin', 'Mr', 'walter.perrin@collaborator.com', 'Artiste IA', 84),
('Yasmine', 'Menard', 'Mme', 'yasmine.menard@collaborator.com', 'Actrice', 85),
('Zian', 'Dubois', 'Mr', 'zian.dubois@collaborator.com', 'Scénariste', 85),
('Amelia', 'Bonnet', 'Mme', 'amelia.bonnet@collaborator.com', 'Compositeur IA', 86),
('Brendan', 'Durand', 'Mr', 'brendan.durand@collaborator.com', 'Acteur', 86),
('Chloe', 'Roussel', 'Mme', 'chloe.roussel@collaborator.com', 'Scénariste', 87),
('Dylan', 'Fournier', 'Mr', 'dylan.fournier@collaborator.com', 'Artiste VFX', 87),
('Elodie', 'Mercier', 'Mme', 'elodie.mercier@collaborator.com', 'Actrice', 88),
('Felix', 'Blanc', 'Mr', 'felix.blanc@collaborator.com', 'Scénariste', 88),
('Gabrielle', 'Moreau', 'Mme', 'gabrielle.moreau@collaborator.com', 'Designer Sonore', 89),
('Hadrien', 'Thomas', 'Mr', 'hadrien.thomas@collaborator.com', 'Technicien rendu', 89),
('Iris', 'Robert', 'Mme', 'iris.robert@collaborator.com', 'Actrice', 90),
('Jason', 'Richard', 'Mr', 'jason.richard@collaborator.com', 'Scénariste', 90),
('Katia', 'Petit', 'Mme', 'katia.petit@collaborator.com', 'Composition musicale IA', 91),
('Leo', 'Leroy', 'Mr', 'leo.leroy@collaborator.com', 'Acteur', 91),
('Manon', 'Simon', 'Mme', 'manon.simon@collaborator.com', 'Auteur dialogue', 92),
('Niels', 'Fournier', 'Mr', 'niels.fournier@collaborator.com', 'Visualisateur 3D', 92),
('Oceane', 'Dupuis', 'Mme', 'oceane.dupuis@collaborator.com', 'Actrice', 93),
('Pierre', 'Garcia', 'Mr', 'pierre.garcia@collaborator.com', 'Scénariste', 93),
('Romain', 'Blanc', 'Mr', 'romain.blanc@collaborator.com', 'Ingénieur du son', 94),
('Sarah', 'Thomas', 'Mme', 'sarah.thomas@collaborator.com', 'Actrice', 94),
('Theo', 'Robert', 'Mr', 'theo.robert@collaborator.com', 'Auteur', 95),
('Ursula', 'Richard', 'Mme', 'ursula.richard@collaborator.com', 'Artiste IA', 95),
('Valentin', 'Dubois', 'Mr', 'valentin.dubois@collaborator.com', 'Acteur', 96),
('Wendy', 'Laurent', 'Mme', 'wendy.laurent@collaborator.com', 'Scénariste', 96),
('Yvan', 'Faure', 'Mr', 'yvan.faure@collaborator.com', 'Compositeur IA', 97),
('Zelie', 'Lambert', 'Mme', 'zelie.lambert@collaborator.com', 'Actrice', 97),
('Arthur', 'Vincent', 'Mr', 'arthur.vincent@collaborator.com', 'Scénariste', 98),
('Betty', 'Lefebvre', 'Mme', 'betty.lefebvre@collaborator.com', 'Artiste VFX', 98),
('Charles', 'Meyer', 'Mr', 'charles.meyer@collaborator.com', 'Actrice', 99),
('Diana', 'Andre', 'Mme', 'diana.andre@collaborator.com', 'Scénariste', 99),
('Eric', 'Louis', 'Mr', 'eric.louis@collaborator.com', 'Designer Sonore', 100),
('Fanny', 'Michel', 'Mme', 'fanny.michel@collaborator.com', 'Technicien rendu', 100),
('Gael', 'Giraud', 'Mr', 'gael.giraud@collaborator.com', 'Acteur', 101),
('Helene', 'Morel', 'Mme', 'helene.morel@collaborator.com', 'Scénariste', 101),
('Ivan', 'Rousseau', 'Mr', 'ivan.rousseau@collaborator.com', 'Composition musicale IA', 102),
('Justine', 'Dupont', 'Mme', 'justine.dupont@collaborator.com', 'Actrice', 102),
('Kyle', 'Leroux', 'Mr', 'kyle.leroux@collaborator.com', 'Auteur dialogue', 103),
('Lina', 'Garnier', 'Mme', 'lina.garnier@collaborator.com', 'Visualisateur 3D', 103),
('Maxence', 'Bertrand', 'Mr', 'maxence.bertrand@collaborator.com', 'Acteur', 104);


--
-- Data for table `image`
-- (Add 1 image per movie from ID 1 to 104)
--
INSERT INTO `image` (`url`, `created_at`, `movie_id`) VALUES
('https://via.placeholder.com/1920x1080.png?text=Movie+1+Poster', NOW(), 1),
('https://via.placeholder.com/1920x1080.png?text=Movie+2+Poster', NOW(), 2),
('https://via.placeholder.com/1920x1080.png?text=Movie+3+Poster', NOW(), 3),
('https://via.placeholder.com/1920x1080.png?text=Movie+4+Poster', NOW(), 4),
('https://via.placeholder.com/1920x1080.png?text=Movie+5+Poster', NOW(), 5),
('https://via.placeholder.com/1920x1080.png?text=Movie+6+Poster', NOW(), 6),
('https://via.placeholder.com/1920x1080.png?text=Movie+7+Poster', NOW(), 7),
('https://via.placeholder.com/1920x1080.png?text=Movie+8+Poster', NOW(), 8),
('https://via.placeholder.com/1920x1080.png?text=Movie+9+Poster', NOW(), 9),
('https://via.placeholder.com/1920x1080.png?text=Movie+10+Poster', NOW(), 10),
('https://via.placeholder.com/1920x1080.png?text=Movie+11+Poster', NOW(), 11),
('https://via.placeholder.com/1920x1080.png?text=Movie+12+Poster', NOW(), 12),
('https://via.placeholder.com/1920x1080.png?text=Movie+13+Poster', NOW(), 13),
('https://via.placeholder.com/1920x1080.png?text=Movie+14+Poster', NOW(), 14),
('https://via.placeholder.com/1920x1080.png?text=Movie+15+Poster', NOW(), 15),
('https://via.placeholder.com/1920x1080.png?text=Movie+16+Poster', NOW(), 16),
('https://via.placeholder.com/1920x1080.png?text=Movie+17+Poster', NOW(), 17),
('https://via.placeholder.com/1920x1080.png?text=Movie+18+Poster', NOW(), 18),
('https://via.placeholder.com/1920x1080.png?text=Movie+19+Poster', NOW(), 19),
('https://via.placeholder.com/1920x1080.png?text=Movie+20+Poster', NOW(), 20),
('https://via.placeholder.com/1920x1080.png?text=Movie+21+Poster', NOW(), 21),
('https://via.placeholder.com/1920x1080.png?text=Movie+22+Poster', NOW(), 22),
('https://via.placeholder.com/1920x1080.png?text=Movie+23+Poster', NOW(), 23),
('https://via.placeholder.com/1920x1080.png?text=Movie+24+Poster', NOW(), 24),
('https://via.placeholder.com/1920x1080.png?text=Movie+25+Poster', NOW(), 25),
('https://via.placeholder.com/1920x1080.png?text=Movie+26+Poster', NOW(), 26),
('https://via.placeholder.com/1920x1080.png?text=Movie+27+Poster', NOW(), 27),
('https://via.placeholder.com/1920x1080.png?text=Movie+28+Poster', NOW(), 28),
('https://via.placeholder.com/1920x1080.png?text=Movie+29+Poster', NOW(), 29),
('https://via.placeholder.com/1920x1080.png?text=Movie+30+Poster', NOW(), 30),
('https://via.placeholder.com/1920x1080.png?text=Movie+31+Poster', NOW(), 31),
('https://via.placeholder.com/1920x1080.png?text=Movie+32+Poster', NOW(), 32),
('https://via.placeholder.com/1920x1080.png?text=Movie+33+Poster', NOW(), 33),
('https://via.placeholder.com/1920x1080.png?text=Movie+34+Poster', NOW(), 34),
('https://via.placeholder.com/1920x1080.png?text=Movie+35+Poster', NOW(), 35),
('https://via.placeholder.com/1920x1080.png?text=Movie+36+Poster', NOW(), 36),
('https://via.placeholder.com/1920x1080.png?text=Movie+37+Poster', NOW(), 37),
('https://via.placeholder.com/1920x1080.png?text=Movie+38+Poster', NOW(), 38),
('https://via.placeholder.com/1920x1080.png?text=Movie+39+Poster', NOW(), 39),
('https://via.placeholder.com/1920x1080.png?text=Movie+40+Poster', NOW(), 40),
('https://via.placeholder.com/1920x1080.png?text=Movie+41+Poster', NOW(), 41),
('https://via.placeholder.com/1920x1080.png?text=Movie+42+Poster', NOW(), 42),
('https://via.placeholder.com/1920x1080.png?text=Movie+43+Poster', NOW(), 43),
('https://via.placeholder.com/1920x1080.png?text=Movie+44+Poster', NOW(), 44),
('https://via.placeholder.com/1920x1080.png?text=Movie+45+Poster', NOW(), 45),
('https://via.placeholder.com/1920x1080.png?text=Movie+46+Poster', NOW(), 46),
('https://via.placeholder.com/1920x1080.png?text=Movie+47+Poster', NOW(), 47),
('https://via.placeholder.com/1920x1080.png?text=Movie+48+Poster', NOW(), 48),
('https://via.placeholder.com/1920x1080.png?text=Movie+49+Poster', NOW(), 49),
('https://via.placeholder.com/1920x1080.png?text=Movie+50+Poster', NOW(), 50),
('https://via.placeholder.com/1920x1080.png?text=Movie+51+Poster', NOW(), 51),
('https://via.placeholder.com/1920x1080.png?text=Movie+52+Poster', NOW(), 52),
('https://via.placeholder.com/1920x1080.png?text=Movie+53+Poster', NOW(), 53),
('https://via.placeholder.com/1920x1080.png?text=Movie+54+Poster', NOW(), 54),
('https://via.placeholder.com/1920x1080.png?text=Movie+55+Poster', NOW(), 55),
('https://via.placeholder.com/1920x1080.png?text=Movie+56+Poster', NOW(), 56),
('https://via.placeholder.com/1920x1080.png?text=Movie+57+Poster', NOW(), 57),
('https://via.placeholder.com/1920x1080.png?text=Movie+58+Poster', NOW(), 58),
('https://via.placeholder.com/1920x1080.png?text=Movie+59+Poster', NOW(), 59),
('https://via.placeholder.com/1920x1080.png?text=Movie+60+Poster', NOW(), 60),
('https://via.placeholder.com/1920x1080.png?text=Movie+61+Poster', NOW(), 61),
('https://via.placeholder.com/1920x1080.png?text=Movie+62+Poster', NOW(), 62),
('https://via.placeholder.com/1920x1080.png?text=Movie+63+Poster', NOW(), 63),
('https://via.placeholder.com/1920x1080.png?text=Movie+64+Poster', NOW(), 64),
('https://via.placeholder.com/1920x1080.png?text=Movie+65+Poster', NOW(), 65),
('https://via.placeholder.com/1920x1080.png?text=Movie+66+Poster', NOW(), 66),
('https://via.placeholder.com/1920x1080.png?text=Movie+67+Poster', NOW(), 67),
('https://via.placeholder.com/1920x1080.png?text=Movie+68+Poster', NOW(), 68),
('https://via.placeholder.com/1920x1080.png?text=Movie+69+Poster', NOW(), 69),
('https://via.placeholder.com/1920x1080.png?text=Movie+70+Poster', NOW(), 70),
('https://via.placeholder.com/1920x1080.png?text=Movie+71+Poster', NOW(), 71),
('https://via.placeholder.com/1920x1080.png?text=Movie+72+Poster', NOW(), 72),
('https://via.placeholder.com/1920x1080.png?text=Movie+73+Poster', NOW(), 73),
('https://via.placeholder.com/1920x1080.png?text=Movie+74+Poster', NOW(), 74),
('https://via.placeholder.com/1920x1080.png?text=Movie+75+Poster', NOW(), 75),
('https://via.placeholder.com/1920x1080.png?text=Movie+76+Poster', NOW(), 76),
('https://via.placeholder.com/1920x1080.png?text=Movie+77+Poster', NOW(), 77),
('https://via.placeholder.com/1920x1080.png?text=Movie+78+Poster', NOW(), 78),
('https://via.placeholder.com/1920x1080.png?text=Movie+79+Poster', NOW(), 79),
('https://via.placeholder.com/1920x1080.png?text=Movie+80+Poster', NOW(), 80),
('https://via.placeholder.com/1920x1080.png?text=Movie+81+Poster', NOW(), 81),
('https://via.placeholder.com/1920x1080.png?text=Movie+82+Poster', NOW(), 82),
('https://via.placeholder.com/1920x1080.png?text=Movie+83+Poster', NOW(), 83),
('https://via.placeholder.com/1920x1080.png?text=Movie+84+Poster', NOW(), 84),
('https://via.placeholder.com/1920x1080.png?text=Movie+85+Poster', NOW(), 85),
('https://via.placeholder.com/1920x1080.png?text=Movie+86+Poster', NOW(), 86),
('https://via.placeholder.com/1920x1080.png?text=Movie+87+Poster', NOW(), 87),
('https://via.placeholder.com/1920x1080.png?text=Movie+88+Poster', NOW(), 88),
('https://via.placeholder.com/1920x1080.png?text=Movie+89+Poster', NOW(), 89),
('https://via.placeholder.com/1920x1080.png?text=Movie+90+Poster', NOW(), 90),
('https://via.placeholder.com/1920x1080.png?text=Movie+91+Poster', NOW(), 91),
('https://via.placeholder.com/1920x1080.png?text=Movie+92+Poster', NOW(), 92),
('https://via.placeholder.com/1920x1080.png?text=Movie+93+Poster', NOW(), 93),
('https://via.placeholder.com/1920x1080.png?text=Movie+94+Poster', NOW(), 94),
('https://via.placeholder.com/1920x1080.png?text=Movie+95+Poster', NOW(), 95),
('https://via.placeholder.com/1920x1080.png?text=Movie+96+Poster', NOW(), 96),
('https://via.placeholder.com/1920x1080.png?text=Movie+97+Poster', NOW(), 97),
('https://via.placeholder.com/1920x1080.png?text=Movie+98+Poster', NOW(), 98),
('https://via.placeholder.com/1920x1080.png?text=Movie+99+Poster', NOW(), 99),
('https://via.placeholder.com/1920x1080.png?text=Movie+100+Poster', NOW(), 100),
('https://via.placeholder.com/1920x1080.png?text=Movie+101+Poster', NOW(), 101),
('https://via.placeholder.com/1920x1080.png?text=Movie+102+Poster', NOW(), 102),
('https://via.placeholder.com/1920x1080.png?text=Movie+103+Poster', NOW(), 103),
('https://via.placeholder.com/1920x1080.png?text=Movie+104+Poster', NOW(), 104);


--
-- Data for table `movie_tag`
-- (Assign 2-3 random tags to each movie from ID 1 to 104)
--
INSERT INTO `movie_tag` (`movie_id`, `tag_id`) VALUES
(1, 1), (1, 5), (2, 2), (2, 6), (3, 3), (3, 5), (4, 1), (4, 2),
(5, 1), (5, 4), (6, 2), (6, 3), (7, 1), (7, 5), (8, 2), (8, 4),
(9, 3), (9, 6), (10, 1), (10, 2), (11, 4), (11, 5), (12, 1), (12, 3),
(13, 2), (13, 6), (14, 1), (14, 4), (15, 3), (15, 5), (16, 1), (16, 2),
(17, 4), (17, 6), (18, 1), (18, 3), (19, 2), (19, 5), (20, 1), (20, 4),
(21, 3), (21, 6), (22, 1), (22, 2), (23, 4), (23, 5), (24, 1), (24, 3),
(25, 2), (25, 6), (26, 1), (26, 4), (27, 3), (27, 5), (28, 1), (28, 2),
(29, 4), (29, 6), (30, 1), (30, 3), (31, 2), (31, 5), (32, 1), (32, 4),
(33, 3), (33, 6), (34, 1), (34, 2), (35, 4), (35, 5), (36, 1), (36, 3),
(37, 2), (37, 6), (38, 1), (38, 4), (39, 3), (39, 5), (40, 1), (40, 2),
(41, 4), (41, 6), (42, 1), (42, 3), (43, 2), (43, 5), (44, 1), (44, 4),
(45, 3), (45, 6), (46, 1), (46, 2), (47, 4), (47, 5), (48, 1), (48, 3),
(49, 2), (49, 6), (50, 1), (50, 4), (51, 3), (51, 5), (52, 1), (52, 2),
(53, 4), (53, 6), (54, 1), (54, 3), (55, 2), (55, 5), (56, 1), (56, 4),
(57, 3), (57, 6), (58, 1), (58, 2), (59, 4), (59, 5), (60, 1), (60, 3),
(61, 2), (61, 6), (62, 1), (62, 4), (63, 3), (63, 5), (64, 1), (64, 2),
(65, 4), (65, 6), (66, 1), (66, 3), (67, 2), (67, 5), (68, 1), (68, 4),
(69, 3), (69, 6), (70, 1), (70, 2), (71, 4), (71, 5), (72, 1), (72, 3),
(73, 2), (73, 6), (74, 1), (74, 4), (75, 3), (75, 5), (76, 1), (76, 2),
(77, 4), (77, 6), (78, 1), (78, 3), (79, 2), (79, 5), (80, 1), (80, 4),
(81, 3), (81, 6), (82, 1), (82, 2), (83, 4), (83, 5), (84, 1), (84, 3),
(85, 2), (85, 6), (86, 1), (86, 4), (87, 3), (87, 5), (88, 1), (88, 2),
(89, 4), (89, 6), (90, 1), (90, 3), (91, 2), (91, 5), (92, 1), (92, 4),
(93, 3), (93, 6), (94, 1), (94, 2), (95, 4), (95, 5), (96, 1), (96, 3),
(97, 2), (97, 6), (98, 1), (98, 4), (99, 3), (99, 5), (100, 1), (100, 2),
(101, 4), (101, 6), (102, 1), (102, 3), (103, 2), (103, 5), (104, 1), (104, 4);

--
-- Data for table `rating`
-- (Jury members (user ID 2) and other users (user ID 3, 4) rate a subset of movies)
-- Assign ~200 ratings in total (avg ~2 per movie, across users)
--
INSERT INTO `rating` (`user_id`, `movie_id`, `score_creativity`, `score_technical`, `score_message`, `comment`, `score_total`, `created_at`) VALUES
(2, 1, 8, 9, 7, 'Concept très original et visuellement impressionnant. L''IA est utilisée à bon escient.', 8.0, NOW()),
(2, 3, 9, 8, 9, 'Une histoire touchante et une animation fluide. Un futur grand nom du cinéma d''animation.', 8.6, NOW()),
(2, 4, 7, 7, 8, 'Très belle exploration thématique, l''exécution visuelle est innovante mais parfois inégale.', 7.3, NOW()),
(2, 5, 8, 7, 8, 'Très intéressant, le rythme est parfait pour un court.', 7.6, NOW()),
(3, 5, 6, 7, 7, 'Pas mal du tout, bonne surprise pour de l''IA.', 6.6, NOW()),
(4, 5, 9, 8, 9, 'Époustouflant, la qualité de production est bluffante.', 8.6, NOW()),
(2, 6, 7, 6, 7, 'Une bonne idée, mais l''exécution technique laisse parfois à désirer.', 6.6, NOW()),
(3, 7, 8, 8, 8, 'Visuellement captivant, j''aimerais en voir plus.', 8.0, NOW()),
(4, 8, 7, 7, 6, 'Une histoire un peu faible, mais des images superbes.', 7.0, NOW()),
(2, 9, 9, 9, 9, 'Un chef-d''œuvre d''animation IA !', 9.0, NOW()),
(3, 10, 6, 5, 6, 'Intéressant mais peu marquant.', 5.6, NOW()),
(4, 11, 8, 8, 7, 'Très bon court, l''IA ouvre de nouvelles portes.', 7.6, NOW()),
(2, 12, 7, 8, 7, 'Beaucoup de potentiel, encore quelques imperfections.', 7.3, NOW()),
(3, 13, 9, 8, 9, 'Impressionnant, le message est puissant.', 8.6, NOW()),
(4, 14, 6, 7, 6, 'Original, mais la narration est un peu confuse.', 6.3, NOW()),
(2, 15, 8, 8, 8, 'Un très bon exemple de ce que l''IA peut faire.', 8.0, NOW()),
(3, 16, 7, 6, 7, 'Bien réalisé, mais manque d''impact émotionnel.', 6.6, NOW()),
(4, 17, 8, 9, 8, 'Étonnant de voir une telle qualité.', 8.3, NOW()),
(2, 18, 9, 8, 9, 'Superbe, une vraie œuvre d''art numérique.', 8.6, NOW()),
(3, 19, 6, 6, 6, 'Simple mais efficace.', 6.0, NOW()),
(4, 20, 7, 7, 7, 'Intrigue bien menée.', 7.0, NOW()),
(2, 21, 8, 7, 8, 'Très beau visuel.', 7.6, NOW()),
(3, 22, 9, 9, 8, 'Techniquement parfait.', 8.6, NOW()),
(4, 23, 7, 6, 7, 'Une belle expérience.', 6.6, NOW()),
(2, 24, 8, 8, 9, 'Innovant et touchant.', 8.3, NOW()),
(3, 25, 6, 7, 6, 'Potentiel inexploité.', 6.3, NOW()),
(4, 26, 8, 7, 8, 'Très bon pour le genre.', 7.6, NOW()),
(2, 27, 9, 9, 9, 'Absolument génial !', 9.0, NOW()),
(3, 28, 7, 7, 7, 'Une histoire bien racontée.', 7.0, NOW()),
(4, 29, 8, 8, 7, 'Très original.', 7.6, NOW()),
(2, 30, 6, 5, 6, 'Peut mieux faire.', 5.6, NOW()),
(3, 31, 8, 9, 8, 'Impressionnant.', 8.3, NOW()),
(4, 32, 7, 7, 6, 'Correct.', 6.6, NOW()),
(2, 33, 9, 8, 9, 'Une vraie pépite.', 8.6, NOW()),
(3, 34, 6, 7, 7, 'Plaisant à regarder.', 6.6, NOW()),
(4, 35, 8, 8, 8, 'Visuellement riche.', 8.0, NOW()),
(2, 36, 7, 6, 7, 'Manque de profondeur.', 6.6, NOW()),
(3, 37, 8, 9, 8, 'Très prometteur.', 8.3, NOW()),
(4, 38, 9, 8, 9, 'Formidable.', 8.6, NOW()),
(2, 39, 6, 6, 6, 'Simple.', 6.0, NOW()),
(3, 40, 7, 7, 7, 'Bien.', 7.0, NOW()),
(4, 41, 8, 7, 8, 'Beau travail.', 7.6, NOW()),
(2, 42, 9, 9, 8, 'Excellent.', 8.6, NOW()),
(3, 43, 7, 6, 7, 'Pas mal.', 6.6, NOW()),
(4, 44, 8, 8, 9, 'Super.', 8.3, NOW()),
(2, 45, 6, 7, 6, 'Bof.', 6.3, NOW()),
(3, 46, 8, 7, 8, 'A voir.', 7.6, NOW()),
(4, 47, 9, 9, 9, 'Magistral.', 9.0, NOW()),
(2, 48, 7, 7, 7, 'Bien fait.', 7.0, NOW()),
(3, 49, 8, 8, 7, 'Créatif.', 7.6, NOW()),
(4, 50, 6, 5, 6, 'Moyen.', 5.6, NOW()),
(2, 51, 8, 9, 8, 'Fantastique.', 8.3, NOW()),
(3, 52, 7, 7, 6, 'Ok.', 6.6, NOW()),
(4, 53, 9, 8, 9, 'Génial.', 8.6, NOW()),
(2, 54, 6, 7, 7, 'Peut mieux faire.', 6.6, NOW()),
(3, 55, 8, 8, 8, 'Impressionnant.', 8.0, NOW()),
(4, 56, 7, 6, 7, 'Pas mal du tout.', 6.6, NOW()),
(2, 57, 8, 9, 8, 'Top.', 8.3, NOW()),
(3, 58, 9, 8, 9, 'Excellent.', 8.6, NOW()),
(4, 59, 6, 6, 6, 'Passable.', 6.0, NOW()),
(2, 60, 7, 7, 7, 'Intéressant.', 7.0, NOW()),
(3, 61, 8, 7, 8, 'Original.', 7.6, NOW()),
(4, 62, 9, 9, 8, 'Sublime.', 8.6, NOW()),
(2, 63, 7, 6, 7, 'Simple mais efficace.', 6.6, NOW()),
(3, 64, 8, 8, 9, 'Très bon.', 8.3, NOW()),
(4, 65, 6, 7, 6, 'À améliorer.', 6.3, NOW()),
(2, 66, 8, 7, 8, 'Créatif.', 7.6, NOW()),
(3, 67, 9, 9, 9, 'Parfait.', 9.0, NOW()),
(4, 68, 7, 7, 7, 'Bien conçu.', 7.0, NOW()),
(2, 69, 8, 8, 7, 'Intéressant.', 7.6, NOW()),
(3, 70, 6, 5, 6, 'Manque de pep.', 5.6, NOW()),
(4, 71, 8, 9, 8, 'Très bonne idée.', 8.3, NOW()),
(2, 72, 7, 7, 6, 'Correct.', 6.6, NOW()),
(3, 73, 9, 8, 9, 'Exceptionnel.', 8.6, NOW()),
(4, 74, 6, 7, 7, 'Plaisant.', 6.6, NOW()),
(2, 75, 8, 8, 8, 'Très beau.', 8.0, NOW()),
(3, 76, 7, 6, 7, 'Un peu long.', 6.6, NOW()),
(4, 77, 8, 9, 8, 'Génial.', 8.3, NOW()),
(2, 78, 9, 8, 9, 'Magnifique.', 8.6, NOW()),
(3, 79, 6, 6, 6, 'Décevant.', 6.0, NOW()),
(4, 80, 7, 7, 7, 'Prometteur.', 7.0, NOW()),
(2, 81, 8, 7, 8, 'Très cool.', 7.6, NOW()),
(3, 82, 9, 9, 8, 'Parfait.', 8.6, NOW()),
(4, 83, 7, 6, 7, 'À revoir.', 6.6, NOW()),
(2, 84, 8, 8, 9, 'Splendide.', 8.3, NOW()),
(3, 85, 6, 7, 6, 'Manque d''originalité.', 6.3, NOW()),
(4, 86, 8, 7, 8, 'Très bien.', 7.6, NOW()),
(2, 87, 9, 9, 9, 'Impressionnant.', 9.0, NOW()),
(3, 88, 7, 7, 7, 'Bonne réalisation.', 7.0, NOW()),
(4, 89, 8, 8, 7, 'Innovant.', 7.6, NOW()),
(2, 90, 6, 5, 6, 'Faible.', 5.6, NOW()),
(3, 91, 8, 9, 8, 'Très efficace.', 8.3, NOW()),
(4, 92, 7, 7, 6, 'Acceptable.', 6.6, NOW()),
(2, 93, 9, 8, 9, 'Formidable.', 8.6, NOW()),
(3, 94, 6, 7, 7, 'Simple.', 6.6, NOW()),
(4, 95, 8, 8, 8, 'Beau.', 8.0, NOW()),
(2, 96, 7, 6, 7, 'Mou.', 6.6, NOW()),
(3, 97, 8, 9, 8, 'Prometteur.', 8.3, NOW()),
(4, 98, 9, 8, 9, 'Excellent.', 8.6, NOW()),
(2, 99, 6, 6, 6, 'Court.', 6.0, NOW()),
(3, 100, 7, 7, 7, 'Passe-partout.', 7.0, NOW()),
(4, 101, 8, 7, 8, 'Très beau visuel.', 7.6, NOW()),
(2, 102, 9, 9, 8, 'Techniquement impeccable.', 8.6, NOW()),
(3, 103, 7, 6, 7, 'Une bonne idée.', 6.6, NOW()),
(4, 104, 8, 8, 9, 'Innovant et unique.', 8.3, NOW());


--
-- Data for table `participant`
-- (Adding more participants)
--
INSERT INTO `participant` (`firstname`, `lastname`, `email`, `mobile`, `job`, `created_at`) VALUES
('Sophia', 'Lamy', 'sophia.lamy@participant.com', '0611223344', 'Critique Cinéma', NOW()),
('Lucas', 'Dupont', 'lucas.dupont@participant.com', '0655667788', 'Étudiant', NOW()),
('Emma', 'Bernard', 'emma.bernard@participant.com', '0699887766', 'Passionné IA', NOW()),
('Gabriel', 'Dubois', 'gabriel.dubois@participant.com', '0612345678', 'Développeur IA', NOW()),
('Chloé', 'Petit', 'chloe.petit@participant.com', '0623456789', 'Journaliste Tech', NOW());


--
-- Data for table `event`
-- (Adding more events linked to Festival ID 1)
--
INSERT INTO `event` (`id`, `title`, `start_at`, `end_at`, `capacity`, `remaining_seats`, `location`, `description`, `status`, `festival_id`) VALUES
(4, 'Conférence: IA et Éthique', '2024-10-16 10:00:00', '2024-10-16 12:00:00', 80, 80, 'Amphithéâtre', 'Discussion sur les enjeux éthiques de l''IA dans la création artistique.', 'Ouvert', 1),
(5, 'Atelier: Créer son court-métrage IA', '2024-10-17 09:00:00', '2024-10-17 13:00:00', 30, 30, 'Salle Atelier 1', 'Session pratique pour apprendre les bases de la création vidéo par IA.', 'Ouvert', 1),
(6, 'Table Ronde: Financement des projets IA', '2024-10-18 14:00:00', '2024-10-18 16:00:00', 70, 70, 'Salle de Conférence', 'Débat sur les opportunités et défis de financement pour les films générés par IA.', 'Ouvert', 1);


--
-- Data for table `books`
-- (Linking participants to events)
--
INSERT INTO `books` (`participant_id`, `event_id`) VALUES
(1, 4), -- Chris Nolan booked for Conférence: IA et Éthique
(2, 5), -- Denis Villeneuve booked for Atelier: Créer son court-métrage IA
(3, 4), -- Kathryn Bigelow booked for Conférence: IA et Éthique
(3, 6), -- Kathryn Bigelow booked for Table Ronde: Financement des projets IA
(4, 5), -- Sophia Lamy booked for Atelier: Créer son court-métrage IA
(5, 6); -- Lucas Dupont booked for Table Ronde: Financement des projets IA

SET FOREIGN_KEY_CHECKS=1; -- Re-enable foreign key checks